[package]
name = "tickets-search"
version = "0.1.0"
authors = ["twissel <twissel@gmail.com>"]

[dependencies]
actix = "0.5"
actix-web = "0.6"
futures = "0.1"
serde = "1.0.43"
serde_derive = "1.0.43"
serde_json = "1.0.16"
chrono = {version = "0.4.4", features = ["serde"]}
petgraph = "0.4.12"
